name: deploy
on:
  push:
    branches:
      - main

jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: up9cloud/action-rsync@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PORT: ${{ secrets.SSH_PORT }}
          USER: ${{ secrets.SSH_USER }}
          SOURCE: ./
          TARGET: /var/www/html/finpro80/
          VERBOSE: true
          ARGS: -az --exclude=/.git/

          PRE_SCRIPT: |
            echo start at:
            date -u
          POST_SCRIPT: "echo done at: && date -u"
