name: deploy
on:
  push:
    branches:
      - main

jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: up9cloud/action-rsync@master
        env:
          HOST: 103.189.235.167
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER: final
          SOURCE: ./
          TARGET: /var/www/html/finpro80/
          VERBOSE: true
          SSH_ARGS: '-p 12211 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=quiet
          ARGS: -az --exclude=/.git/

          PRE_SCRIPT: |
            echo start at:
            date -u
          POST_SCRIPT: "echo done at: && date -u"
